spring:
  datasource:
    url: ENC(Dqz6/UyiJdUvW/k/dHoUXV7BzVuW2HiGVhQHJAOgg+lz2KWsQhEWgBuw4cRejXieL4MBsQjBp7SF6G/pFfFKDi3fXebYXmgIg1lbSAMTjIpQRGqM/52ORkWo6wkblIG/bX2Ahx9ZX/0aTougC6C6hSRl4Vp4pLjFFtAJioAnaToufTpBNGppYw==)
    username: ENC(671Ur2dsRWvoUeeUwbb6hQ==)
    password: ENC(BLSnCvWX1vSqMQsPlM0zAI94uEiEH4eA)
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

cloud:
  aws:
    credentials:
      access-key: ENC(IwK9G3Kspc9FECjdnwK59dSM+iyqcUzxVKjtbfodcpY=)
      secret-key: ENC(H4mew6/KTk3Ga08ogJLvF7+BlcHTu5HSx+t024VKWkFam50sHKl6VOORmEjwldJXH/nb/mJCC0k=)
    region:
      static: ap-northeast-2
    s3:
      bucket: ENC(D3Ub+IYIZXtIEkzni48cB/SotwB7BPlRAdgGsEP9yVs=)
    stack:
      auto: false