spring:
  application:
    name: wear
  config:
    import: classpath:common.yml
  profiles:
    default: "local"
    group:
      local:
        - common
      dev:
        - common
      prod:
        - common

server:
  servlet:
    context-path: /api/v1
