spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(RdXCoZqUaKTO9DzeUbOWRWdiSNF4aU+fAwuTjwYtqlS8vqaTEBDWsXblBYa7hLUv/etsrZBbOVYUEm47+Z5gtj4qDbwVo5znFm80arOPw3mWtXiohoEBsdYAzNdW8d4k23ArJWiag0UGma8mQEBTJdgOYxykPUgRikDkDmo1/yCF3GtXYMkkGQ==)
    username: ENC(4kM/SGoI83Ao2Awdy41Ygw==)
    password: ENC(2V3SaZv9tPg28+dQb03UFRqo1WE+QD1+)
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

cloud:
  aws:
    credentials:
      access-key: ENC(dg+YZMgLhAO8SEBkoPuzwZrfks++GI0uAhxFEOwgSt8=)
      secret-key: ENC(7/25IfLDHcZdwlg1G6bZ+SfMYHMvxGO2m7Flj9exFuEBOoeWOFzIp1rVp1IbS5GRRerdja+k2sE=)
    region:
      static: ap-northeast-2
    s3:
      bucket: ENC(nUpCEKz7QOM3FPB/idcTzOyY7keJIb3OPv+0bFb8LXA=)
    stack:
      auto: false