spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wearweather
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
